---
title: "About"
---

Originally I came to Washington University in St. Louis as a Chinese and Art History double major, before discovering my interest in Earth Science. Studying Hydrology and Surface Processes, I was fascinated by rivers and how they could move sediments through landscapes. Looking for new experiences, I moved to New York City when I graduated and worked as a Staff Geologist, monitoring soil movement on construction sites to comply with the Resource Conservation and Recovery Act (RCRA).

Currently I am a second-year student at the Bren School getting my Masters in Environmental Science and Management. Since coming to Bren, I have re-discovered my interest in rivers, and am currently working in the Surface Processes Lab here at UCSB studying river migration and movement worldwide. This results of this research could affect flood policy in regions that experience avulsion events, informing when flood prevention measures could be put into place.

Outside of Bren, I love being outside, mainly walking along the beach with friends or going for a run around campus. I also enjoy knitting and crocheting, and host a craft night every week in my apartment.
